{
 "title": "Application Logs",
 "tags": [
  "logs",
  "application"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Java Application Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"java-tomcat\"} | json"
    }
   ]
  },
  {
   "title": "Tomcat Server Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"tomcat\"} | json"
    }
   ]
  },
  {
   "title": "Promtail Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"promtail\"} | json"
    }
   ]
  }
 ]
}