global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'cloudwatch-exporter'
    static_configs:
      - targets: ['cloudwatch-exporter:9106']

  - job_name: 'app-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-backend:8080']

  # L'application mobile ne fournit pas de métriques Prometheus directement
  # Utilisez node-exporter pour surveiller le système hôte
