# Configuration CloudWatch Exporter pour Prometheus
# Ce fichier définit les métriques AWS à collecter via l'API CloudWatch
# Les variables ${aws_region}, ${s3_bucket_name}, etc. sont remplacées lors du déploiement

# Région AWS à surveiller
region: ${aws_region}

# Liste des métriques à collecter
metrics:
  #############################################################################
  # S3 Metrics - Surveillance du bucket S3 pour le stockage des médias
  #############################################################################

  # Taille totale du bucket en octets
  - aws_namespace: AWS/S3
    aws_metric_name: BucketSizeBytes
    aws_dimensions: [BucketName, StorageType]
    aws_statistics: [Average, Maximum]
    aws_dimension_select:
      BucketName: ["${s3_bucket_name}"]
      StorageType: [StandardStorage]
    period_seconds: 86400  # 24 heures (les métriques S3 sont mises à jour quotidiennement)

  # Nombre total d'objets dans le bucket
  - aws_namespace: AWS/S3
    aws_metric_name: NumberOfObjects
    aws_dimensions: [BucketName, StorageType]
    aws_statistics: [Average, Maximum]
    aws_dimension_select:
      BucketName: ["${s3_bucket_name}"]
      StorageType: [AllStorageTypes]
    period_seconds: 86400  # 24 heures

  # Requêtes par type d'opération
  - aws_namespace: AWS/S3
    aws_metric_name: AllRequests
    aws_dimensions: [BucketName, FilterId]
    aws_statistics: [Sum]
    aws_dimension_select:
      BucketName: ["${s3_bucket_name}"]
    period_seconds: 300  # 5 minutes

  #############################################################################
  # RDS Metrics - Surveillance de la base de données MySQL
  #############################################################################

  # Utilisation CPU de l'instance RDS
  - aws_namespace: AWS/RDS
    aws_metric_name: CPUUtilization
    aws_dimensions: [DBInstanceIdentifier]
    aws_statistics: [Average, Maximum]
    period_seconds: 300  # 5 minutes

  # Nombre de connexions à la base de données
  - aws_namespace: AWS/RDS
    aws_metric_name: DatabaseConnections
    aws_dimensions: [DBInstanceIdentifier]
    aws_statistics: [Average, Maximum, Sum]
    period_seconds: 300  # 5 minutes

  # Espace de stockage disponible
  - aws_namespace: AWS/RDS
    aws_metric_name: FreeStorageSpace
    aws_dimensions: [DBInstanceIdentifier]
    aws_statistics: [Average, Minimum]
    period_seconds: 300  # 5 minutes

  # Latence des opérations de lecture
  - aws_namespace: AWS/RDS
    aws_metric_name: ReadLatency
    aws_dimensions: [DBInstanceIdentifier]
    aws_statistics: [Average, Maximum]
    period_seconds: 300  # 5 minutes

  # Latence des opérations d'écriture
  - aws_namespace: AWS/RDS
    aws_metric_name: WriteLatency
    aws_dimensions: [DBInstanceIdentifier]
    aws_statistics: [Average, Maximum]
    period_seconds: 300  # 5 minutes

  #############################################################################
  # EC2 Metrics - Surveillance des instances EC2
  #############################################################################

  # Utilisation CPU
  - aws_namespace: AWS/EC2
    aws_metric_name: CPUUtilization
    aws_dimensions: [InstanceId]
    aws_statistics: [Average, Maximum]
    period_seconds: 300  # 5 minutes

  # Trafic réseau entrant
  - aws_namespace: AWS/EC2
    aws_metric_name: NetworkIn
    aws_dimensions: [InstanceId]
    aws_statistics: [Average, Sum]
    period_seconds: 300  # 5 minutes

  # Trafic réseau sortant
  - aws_namespace: AWS/EC2
    aws_metric_name: NetworkOut
    aws_dimensions: [InstanceId]
    aws_statistics: [Average, Sum]
    period_seconds: 300  # 5 minutes

  # Opérations disque
  - aws_namespace: AWS/EC2
    aws_metric_name: DiskReadOps
    aws_dimensions: [InstanceId]
    aws_statistics: [Average, Sum]
    period_seconds: 300  # 5 minutes

  - aws_namespace: AWS/EC2
    aws_metric_name: DiskWriteOps
    aws_dimensions: [InstanceId]
    aws_statistics: [Average, Sum]
    period_seconds: 300  # 5 minutes
