global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: "ec2-monitoring"
          service: "prometheus"

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: "ec2-monitoring"
          service: "node-exporter"
      - targets: ['ec2-java-tomcat:9100']
        labels:
          instance: "ec2-java-tomcat"
          service: "node-exporter"

  - job_name: 'java-tomcat'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ec2-java-tomcat:8080']
        labels:
          instance: "ec2-java-tomcat"
          service: "java-app"
          type: "application"

  - job_name: 'tomcat-jmx'
    static_configs:
      - targets: ['ec2-java-tomcat:9404']
        labels:
          instance: "ec2-java-tomcat"
          service: "tomcat"
          type: "jmx"

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: "ec2-monitoring"
          service: "cadvisor"
      - targets: ['ec2-java-tomcat:8081']
        labels:
          instance: "ec2-java-tomcat"
          service: "cadvisor"

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          instance: "ec2-monitoring"
          service: "grafana"
