name: 0.5 - Préparation des scripts pour Terraform

# -----------------------------------------------------------------------
# Ce workflow prépare les scripts pour Terraform en les lisant et en les
# stockant dans des variables d'environnement Terraform.
# -----------------------------------------------------------------------

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement de déploiement'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev      # Environnement de développement
          - pre-prod # Environnement de pré-production
          - prod     # Environnement de production

jobs:
  prepare-scripts:
    name: 'Préparation des scripts pour Terraform'
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2: Exécution du script de préparation
      - name: Exécuter le script de préparation
        run: |
          chmod +x scripts/utils/prepare-terraform-scripts.sh
          ./scripts/utils/prepare-terraform-scripts.sh

      # Étape 3: Téléchargement du fichier terraform.tfvars.scripts
      - name: Télécharger le fichier terraform.tfvars.scripts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-scripts
          path: infrastructure/terraform.tfvars.scripts

      # Étape 4: Résumé
      - name: Résumé
        run: |
          echo "## Résumé de la préparation des scripts" >> $GITHUB_STEP_SUMMARY
          echo "* **Environnement:** ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Fichier généré:** infrastructure/terraform.tfvars.scripts" >> $GITHUB_STEP_SUMMARY
          echo "* **Statut:** Terminé ✅" >> $GITHUB_STEP_SUMMARY
          echo "* **Prochaine étape:** Exécuter le workflow 1-infra-deploy-destroy.yml avec l'action 'plan' ou 'apply'" >> $GITHUB_STEP_SUMMARY
