name: 1 - Deploy/Destroy Infrastructure (Terraform)

# -----------------------------------------------------------------------
# Ce workflow gère le déploiement et la destruction de l'infrastructure AWS via Terraform.
# Il utilise le secret GH_PAT au lieu de GITHUB_TOKEN car les noms de secrets personnalisés
# ne doivent pas commencer par GITHUB_ (préfixe réservé aux variables d'environnement GitHub).
# La syntaxe ${{ secrets.GH_PAT || '' }} permet d'utiliser une chaîne vide si le secret
# n'est pas défini, évitant ainsi le blocage du workflow.
# -----------------------------------------------------------------------

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action Terraform à exécuter'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan     # Prévisualiser les changements sans les appliquer
          - apply    # Appliquer les changements à l'infrastructure
          - destroy  # Détruire l'infrastructure existante
      environment:
        description: 'Environnement de déploiement'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev      # Environnement de développement
          - pre-prod # Environnement de pré-production
          - prod     # Environnement de production



# Variables d'environnement globales
env:
  TF_WORKING_DIR: ./infrastructure  # Répertoire contenant les fichiers Terraform
  AWS_REGION: eu-west-3            # Région AWS (Paris)

jobs:
  terraform:
    name: 'Terraform ${{ github.event.inputs.action }}'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      # Étape 1: Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main  # Utilise explicitement la branche main
          fetch-depth: 0  # Récupère tout l'historique pour les tags

      # Étape 2: Configuration de Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">=1.0"  # Version compatible avec le code
          terraform_wrapper: false    # Désactive le wrapper pour une meilleure gestion des erreurs
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} # Token pour Terraform Cloud

      # Étape 3: Configuration des identifiants AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Étape 4: Configuration des variables Terraform Cloud
      - name: Configure Terraform Cloud Variables
        run: |
          # Créer un fichier de configuration pour l'API Terraform Cloud
          cat > ~/.terraformrc << EOF
          credentials "app.terraform.io" {
            token = "${{ secrets.TF_API_TOKEN }}"
          }
          EOF

          # Définir les variables AWS dans Terraform Cloud via l'API
          curl -s -X POST https://app.terraform.io/api/v2/workspaces/ws-${{ secrets.TF_WORKSPACE_ID }}/vars \
            -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            -H "Content-Type: application/vnd.api+json" \
            -d '{
              "data": {
                "type": "vars",
                "attributes": {
                  "key": "aws_access_key",
                  "value": "${{ secrets.AWS_ACCESS_KEY_ID }}",
                  "category": "terraform",
                  "sensitive": true
                }
              }
            }'

          curl -s -X POST https://app.terraform.io/api/v2/workspaces/ws-${{ secrets.TF_WORKSPACE_ID }}/vars \
            -H "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            -H "Content-Type: application/vnd.api+json" \
            -d '{
              "data": {
                "type": "vars",
                "attributes": {
                  "key": "aws_secret_key",
                  "value": "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
                  "category": "terraform",
                  "sensitive": true
                }
              }
            }'

      # Étape 5: Initialisation de Terraform
      - name: Terraform Init
        id: init
        run: terraform init

      # Étape 5: Validation de la configuration Terraform
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # Étape 6: Formatage du code Terraform (vérification uniquement)
      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true  # Ne bloque pas le workflow si le formatage n'est pas correct

      # Étape 7: Planification des changements Terraform
      - name: Terraform Plan
        id: plan
        if: github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply'
        run: |
          echo "::group::Terraform Plan"
          # Créer le fichier de clé SSH si le secret est disponible
          if [ ! -z "${{ secrets.EC2_SSH_PRIVATE_KEY }}" ]; then
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "Clé SSH privée configurée."
          fi

          terraform plan \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="db_name=${{ secrets.DB_NAME || 'yourmedia' }}" \
            -var="ec2_key_pair_name=${{ secrets.EC2_KEY_PAIR_NAME }}" \
            -var="github_token=${{ secrets.GH_PAT || '' }}" \
            -var="repo_owner=${{ github.repository_owner }}" \
            -var="repo_name=${{ github.repository }}" \
            -var="ssh_private_key_path=~/.ssh/id_rsa" \
            -var="ssh_private_key_content='${{ secrets.EC2_SSH_PRIVATE_KEY || '' }}'" \
            -var="ssh_public_key='${{ secrets.EC2_SSH_PUBLIC_KEY || '' }}'" \
            -var="enable_provisioning=${{ secrets.EC2_SSH_PRIVATE_KEY != '' }}" \
            -var="environment=${{ github.event.inputs.environment }}" \
            -no-color \
            -out=tfplan
          echo "::endgroup::"
        continue-on-error: false  # Arrête le workflow si le plan échoue

      # Étape 8: Application des changements Terraform
      - name: Terraform Apply
        id: apply
        if: github.event.inputs.action == 'apply'
        run: |
          echo "::group::Terraform Apply"
          terraform apply -auto-approve tfplan
          echo "::endgroup::"

          # Affiche les outputs après l'application
          echo "\n\n--- Outputs de l'infrastructure ---"
          terraform output

          # Stockage des outputs dans les secrets GitHub
          echo "::group::Stockage des outputs dans les secrets GitHub"
          # Récupération des outputs importants
          # Utilisation de variables locales pour éviter les erreurs si les outputs n'existent pas
          EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip 2>/dev/null || echo "")
          S3_BUCKET_NAME=$(terraform output -raw s3_bucket_name 2>/dev/null || echo "")
          MONITORING_EC2_PUBLIC_IP=$(terraform output -raw monitoring_ec2_public_ip 2>/dev/null || echo "")
          RDS_ENDPOINT=$(terraform output -raw rds_endpoint 2>/dev/null || echo "")
          GRAFANA_URL=$(terraform output -raw grafana_url 2>/dev/null || echo "")
          AMPLIFY_APP_URL=$(terraform output -raw amplify_app_url 2>/dev/null || echo "")

          # Stockage dans les variables d'environnement du workflow
          if [ ! -z "$EC2_PUBLIC_IP" ]; then
            echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
          fi

          if [ ! -z "$S3_BUCKET_NAME" ]; then
            echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> $GITHUB_ENV
          fi

          if [ ! -z "$MONITORING_EC2_PUBLIC_IP" ]; then
            echo "MONITORING_EC2_PUBLIC_IP=$MONITORING_EC2_PUBLIC_IP" >> $GITHUB_ENV
          fi

          if [ ! -z "$RDS_ENDPOINT" ]; then
            echo "RDS_ENDPOINT=$RDS_ENDPOINT" >> $GITHUB_ENV
          fi

          if [ ! -z "$GRAFANA_URL" ]; then
            echo "GRAFANA_URL=$GRAFANA_URL" >> $GITHUB_ENV
          fi

          if [ ! -z "$AMPLIFY_APP_URL" ]; then
            echo "AMPLIFY_APP_URL=$AMPLIFY_APP_URL" >> $GITHUB_ENV
          fi

          echo "::endgroup::"
        continue-on-error: false  # Arrête le workflow si l'application échoue

      # Étape 8.5: Vider le bucket S3 avant la destruction
      - name: Empty S3 Bucket
        id: empty_s3
        if: github.event.inputs.action == 'destroy'
        run: |
          echo "::group::Vidage du bucket S3"
          # Récupérer le nom du bucket S3 depuis les outputs Terraform
          S3_BUCKET_NAME=$(terraform output -raw s3_bucket_name 2>/dev/null || echo "")

          if [ ! -z "$S3_BUCKET_NAME" ]; then
            echo "Vidage du bucket S3: $S3_BUCKET_NAME"
            # Vider le bucket S3
            aws s3 rm s3://$S3_BUCKET_NAME --recursive
            echo "Bucket S3 vidé avec succès."
          else
            echo "Aucun bucket S3 à vider ou nom de bucket non disponible."
          fi
          echo "::endgroup::"
        continue-on-error: true  # Continuer même si le vidage échoue

      # Étape 9: Destruction de l'infrastructure Terraform
      - name: Terraform Destroy
        id: destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          echo "::group::Terraform Destroy"
          # Créer le fichier de clé SSH si le secret est disponible
          if [ ! -z "${{ secrets.EC2_SSH_PRIVATE_KEY }}" ]; then
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "Clé SSH privée configurée."
          fi

          terraform destroy -auto-approve \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="db_name=${{ secrets.DB_NAME || 'yourmedia' }}" \
            -var="ec2_key_pair_name=${{ secrets.EC2_KEY_PAIR_NAME }}" \
            -var="github_token=${{ secrets.GH_PAT || '' }}" \
            -var="repo_owner=${{ github.repository_owner }}" \
            -var="repo_name=${{ github.repository }}" \
            -var="ssh_private_key_path=~/.ssh/id_rsa" \
            -var="ssh_private_key_content='${{ secrets.EC2_SSH_PRIVATE_KEY || '' }}'" \
            -var="ssh_public_key='${{ secrets.EC2_SSH_PUBLIC_KEY || '' }}'" \
            -var="enable_provisioning=${{ secrets.EC2_SSH_PRIVATE_KEY != '' }}" \
            -var="environment=${{ github.event.inputs.environment }}"
          echo "::endgroup::"
        continue-on-error: true  # Continuer même si la destruction échoue pour pouvoir nettoyer les ressources persistantes

      # Étape 9.1: Nettoyage des profils IAM persistants
      - name: Cleanup IAM Profiles
        if: github.event.inputs.action == 'destroy'
        run: |
          echo "::group::Nettoyage des profils IAM persistants"

          # Définir les noms des ressources IAM à nettoyer
          PROJECT_NAME="yourmedia"
          ENVIRONMENT="${{ github.event.inputs.environment }}"
          EC2_PROFILE="${PROJECT_NAME}-${ENVIRONMENT}-ec2-profile"
          MONITORING_PROFILE="${PROJECT_NAME}-${ENVIRONMENT}-monitoring-profile"
          EC2_ROLE="${PROJECT_NAME}-${ENVIRONMENT}-ec2-role-v2"
          MONITORING_ROLE="${PROJECT_NAME}-${ENVIRONMENT}-monitoring-role-v2"

          echo "Nettoyage des profils IAM pour le projet ${PROJECT_NAME} et l'environnement ${ENVIRONMENT}..."

          # Fonction pour supprimer un profil IAM
          delete_instance_profile() {
            local profile_name=$1
            echo "Suppression du profil IAM $profile_name..."

            # Vérifier si le profil existe
            if aws iam get-instance-profile --instance-profile-name $profile_name 2>/dev/null; then
              # Récupérer les rôles attachés au profil
              ROLES=$(aws iam get-instance-profile --instance-profile-name $profile_name --query "InstanceProfile.Roles[*].RoleName" --output text)

              # Détacher les rôles du profil
              for role in $ROLES; do
                echo "Détachement du rôle $role du profil $profile_name..."
                aws iam remove-role-from-instance-profile --instance-profile-name $profile_name --role-name $role
              done

              # Supprimer le profil
              aws iam delete-instance-profile --instance-profile-name $profile_name
              echo "Profil IAM $profile_name supprimé avec succès."
            else
              echo "Le profil IAM $profile_name n'existe pas."
            fi
          }

          # Supprimer les profils IAM
          delete_instance_profile $EC2_PROFILE
          delete_instance_profile $MONITORING_PROFILE

          echo "Nettoyage des profils IAM terminé."
          echo "::endgroup::"
        continue-on-error: true  # Continuer même si le nettoyage échoue

      # Étape 10: Création des secrets GitHub à partir des outputs Terraform
      # Création des secrets GitHub à partir des outputs Terraform
      - name: Create GitHub Secrets from Terraform Outputs
        if: github.event.inputs.action == 'apply'
        uses: gliech/create-github-secret-action@v1
        with:
          name: TF_EC2_PUBLIC_IP
          value: ${{ env.EC2_PUBLIC_IP }}
          pa_token: ${{ secrets.GH_PAT }}
        continue-on-error: true

      - name: Create S3 Bucket Secret
        if: github.event.inputs.action == 'apply' && env.S3_BUCKET_NAME != ''
        uses: gliech/create-github-secret-action@v1
        with:
          name: TF_S3_BUCKET_NAME
          value: ${{ env.S3_BUCKET_NAME }}
          pa_token: ${{ secrets.GH_PAT }}
        continue-on-error: true

      - name: Create Monitoring EC2 Secret
        if: github.event.inputs.action == 'apply' && env.MONITORING_EC2_PUBLIC_IP != ''
        uses: gliech/create-github-secret-action@v1
        with:
          name: TF_MONITORING_EC2_PUBLIC_IP
          value: ${{ env.MONITORING_EC2_PUBLIC_IP }}
          pa_token: ${{ secrets.GH_PAT }}
        continue-on-error: true

      - name: Create RDS Endpoint Secret
        if: github.event.inputs.action == 'apply' && env.RDS_ENDPOINT != ''
        uses: gliech/create-github-secret-action@v1
        with:
          name: TF_RDS_ENDPOINT
          value: ${{ env.RDS_ENDPOINT }}
          pa_token: ${{ secrets.GH_PAT }}
        continue-on-error: true

      - name: Create Grafana URL Secret
        if: github.event.inputs.action == 'apply' && env.GRAFANA_URL != ''
        uses: gliech/create-github-secret-action@v1
        with:
          name: TF_GRAFANA_URL
          value: ${{ env.GRAFANA_URL }}
          pa_token: ${{ secrets.GH_PAT }}
        continue-on-error: true

      - name: Create Amplify App URL Secret
        if: github.event.inputs.action == 'apply' && env.AMPLIFY_APP_URL != ''
        uses: gliech/create-github-secret-action@v1
        with:
          name: TF_AMPLIFY_APP_URL
          value: ${{ env.AMPLIFY_APP_URL }}
          pa_token: ${{ secrets.GH_PAT }}
        continue-on-error: true

      # Étape 11: Résumé de l'exécution
      - name: Summary
        run: |
          echo "## Résumé de l'exécution Terraform" >> $GITHUB_STEP_SUMMARY
          echo "* **Action exécutée:** ${{ github.event.inputs.action }}" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
            echo "* **Outputs stockés dans les secrets GitHub:**" >> $GITHUB_STEP_SUMMARY
            if [ ! -z "$EC2_PUBLIC_IP" ]; then echo "  - TF_EC2_PUBLIC_IP" >> $GITHUB_STEP_SUMMARY; fi
            if [ ! -z "$S3_BUCKET_NAME" ]; then echo "  - TF_S3_BUCKET_NAME" >> $GITHUB_STEP_SUMMARY; fi
            if [ ! -z "$MONITORING_EC2_PUBLIC_IP" ]; then echo "  - TF_MONITORING_EC2_PUBLIC_IP" >> $GITHUB_STEP_SUMMARY; fi
            if [ ! -z "$RDS_ENDPOINT" ]; then echo "  - TF_RDS_ENDPOINT" >> $GITHUB_STEP_SUMMARY; fi
            if [ ! -z "$GRAFANA_URL" ]; then echo "  - TF_GRAFANA_URL" >> $GITHUB_STEP_SUMMARY; fi
            if [ ! -z "$AMPLIFY_APP_URL" ]; then echo "  - TF_AMPLIFY_APP_URL" >> $GITHUB_STEP_SUMMARY; fi
          fi
          echo "* **Branche:** main" >> $GITHUB_STEP_SUMMARY
          echo "* **Région AWS:** ${{ env.AWS_REGION }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Statut:** Succès ✅" >> $GITHUB_STEP_SUMMARY
