name: 3 - Docker Build and Deploy

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to build and deploy'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - mobile
          - monitoring
      deploy:
        description: 'Deploy after build'
        required: true
        default: true
        type: boolean

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version
        id: version
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"

      # Build and push mobile app image
      - name: Build and push mobile app image
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'mobile' }}
        uses: docker/build-push-action@v4
        with:
          context: ./app-react
          file: ./app-react/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:mobile-${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:mobile-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Grafana image
      - name: Build and push Grafana image
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'monitoring' }}
        uses: docker/build-push-action@v4
        with:
          context: ./infrastructure/modules/ec2-monitoring/docker/grafana
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:grafana-${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:grafana-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Prometheus image
      - name: Build and push Prometheus image
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'monitoring' }}
        uses: docker/build-push-action@v4
        with:
          context: ./infrastructure/modules/ec2-monitoring/docker/prometheus
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:prometheus-${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:prometheus-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push SonarQube image
      - name: Build and push SonarQube image
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'monitoring' }}
        uses: docker/build-push-action@v4
        with:
          context: ./infrastructure/modules/ec2-monitoring/docker/sonarqube
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:sonarqube-${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:sonarqube-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "## Docker Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "* **Version:** ${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Target:** ${{ github.event.inputs.target }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Deploy:** ${{ github.event.inputs.deploy }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Docker Hub Repository:** https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "mobile" ]]; then
            echo "* **Mobile App Image:** ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:mobile-${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "monitoring" ]]; then
            echo "* **Grafana Image:** ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:grafana-${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
            echo "* **Prometheus Image:** ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:prometheus-${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
            echo "* **SonarQube Image:** ${{ secrets.DOCKERHUB_USERNAME }}/yourmedia-ecf:sonarqube-${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
          fi

  deploy:
    needs: build-and-push
    if: ${{ github.event.inputs.deploy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.TF_EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy monitoring containers
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'monitoring' }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPO: yourmedia-ecf
          TF_MONITORING_EC2_PUBLIC_IP: ${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}
          GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TF_RDS_ENDPOINT: ${{ secrets.TF_RDS_ENDPOINT }}
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID || 'dummy-id' }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET || 'dummy-secret' }}
        run: |
          chmod +x ./scripts/deploy-containers.sh
          ./scripts/deploy-containers.sh monitoring

      - name: Deploy app containers
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'mobile' }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPO: yourmedia-ecf
          TF_EC2_PUBLIC_IP: ${{ secrets.TF_EC2_PUBLIC_IP }}
        run: |
          chmod +x ./scripts/deploy-containers.sh
          ./scripts/deploy-containers.sh app

      - name: Summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "* **Target:** ${{ github.event.inputs.target }}" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "monitoring" ]]; then
            echo "* **Monitoring URL:** http://${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}:3001" >> $GITHUB_STEP_SUMMARY
            echo "* **Prometheus URL:** http://${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}:9090" >> $GITHUB_STEP_SUMMARY
            echo "* **SonarQube URL:** http://${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}:9000" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "mobile" ]]; then
            echo "* **Mobile App URL:** http://${{ secrets.TF_EC2_PUBLIC_IP }}:3000" >> $GITHUB_STEP_SUMMARY
          fi
