name: 3 - Construction et Déploiement Docker

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action à effectuer'
        required: true
        default: 'both'
        type: choice
        options:
          - build    # Uniquement construire et pousser les images
          - deploy   # Uniquement déployer les images existantes
          - both     # Construire, pousser et déployer les images
      target:
        description: 'Cible à construire et/ou déployer'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - mobile
          - monitoring

jobs:
  build-and-push:
    if: ${{ github.event.inputs.action == 'build' || github.event.inputs.action == 'both' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version
        id: version
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"

      # Build and push mobile app image
      - name: Build and push mobile app image
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'mobile' }}
        uses: docker/build-push-action@v5
        with:
          context: ./app-react
          file: ./app-react/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:mobile-${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:mobile-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Grafana image
      - name: Build and push Grafana image
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'monitoring' }}
        uses: docker/build-push-action@v5
        with:
          context: ./scripts/config/grafana
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:grafana-${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:grafana-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Prometheus image
      - name: Build and push Prometheus image
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'monitoring' }}
        uses: docker/build-push-action@v5
        with:
          context: ./scripts/config/prometheus
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:prometheus-${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:prometheus-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Loki image
      - name: Build and push Loki image
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'monitoring' }}
        uses: docker/build-push-action@v5
        with:
          context: ./scripts/config/loki
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:loki-${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:loki-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Promtail image
      - name: Build and push Promtail image
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'monitoring' }}
        uses: docker/build-push-action@v5
        with:
          context: ./scripts/config/promtail
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:promtail-${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:promtail-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max



      # Install Trivy scanner for security scanning
      - name: Install Trivy scanner
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.45.1
          trivy --version

      # Test Docker images for vulnerabilities
      - name: Test Docker images with Trivy
        run: |
          echo "Scanning Docker images for vulnerabilities..."

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "mobile" ]]; then
            echo "Scanning mobile app image..."
            trivy image --exit-code 0 --severity HIGH,CRITICAL --ignore-unfixed ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:mobile-${{ env.VERSION }} > mobile-scan.txt
          fi

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "monitoring" ]]; then
            echo "Scanning Grafana image..."
            trivy image --exit-code 0 --severity HIGH,CRITICAL --ignore-unfixed ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:grafana-${{ env.VERSION }} > grafana-scan.txt

            echo "Scanning Prometheus image..."
            trivy image --exit-code 0 --severity HIGH,CRITICAL --ignore-unfixed ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:prometheus-${{ env.VERSION }} > prometheus-scan.txt


          fi

      # Test Docker image health checks
      - name: Test Docker image health checks
        run: |
          # Test de santé pour l'application mobile
          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "mobile" ]]; then
            echo "Démarrage du conteneur mobile pour les tests..."
            docker run -d --name mobile-test -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:mobile-${{ env.VERSION }}

            echo "Attente de 15 secondes pour le démarrage du conteneur..."
            sleep 15

            echo "Vérification de l'état de santé de l'application mobile..."
            if curl -s -f http://localhost:3000/ > /dev/null; then
                echo "✅ Le test de santé de l'application mobile a réussi"
            else
                echo "❌ Le test de santé de l'application mobile a échoué"
                echo "Logs du conteneur mobile:"
                docker logs mobile-test
                echo "::warning::Le health check de l'image mobile a échoué"
            fi
            docker stop mobile-test
            docker rm mobile-test
          fi

          # Test de santé pour Grafana
          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "monitoring" ]]; then
            echo "Démarrage du conteneur Grafana pour les tests..."
            docker run -d --name grafana-test -p 3000:3000 \
              -e "GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GF_SECURITY_ADMIN_PASSWORD || 'YourMedia2025!' }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:grafana-${{ env.VERSION }}

            echo "Attente de 15 secondes pour le démarrage du conteneur..."
            sleep 15

            echo "Vérification de l'état de santé de Grafana..."
            if curl -s -f http://localhost:3000/api/health > /dev/null; then
                echo "✅ Le test de santé de Grafana a réussi"
            else
                echo "❌ Le test de santé de Grafana a échoué"
                echo "Logs du conteneur Grafana:"
                docker logs grafana-test
                echo "::warning::Le health check de l'image Grafana a échoué"
            fi
            docker stop grafana-test
            docker rm grafana-test

            # Test de santé pour Prometheus
            echo "Démarrage du conteneur Prometheus pour les tests..."
            docker run -d --name prometheus-test -p 9090:9090 \
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:prometheus-${{ env.VERSION }}

            echo "Attente de 15 secondes pour le démarrage du conteneur..."
            sleep 15

            echo "Vérification de l'état de santé de Prometheus..."
            if curl -s -f http://localhost:9090/-/healthy > /dev/null; then
                echo "✅ Le test de santé de Prometheus a réussi"
            else
                echo "❌ Le test de santé de Prometheus a échoué"
                echo "Logs du conteneur Prometheus:"
                docker logs prometheus-test
                echo "::warning::Le health check de l'image Prometheus a échoué"
            fi
            docker stop prometheus-test
            docker rm prometheus-test


          fi

      - name: Summary
        run: |
          echo "## Résumé de la Construction Docker" >> $GITHUB_STEP_SUMMARY
          echo "* **Version:** ${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Action:** ${{ github.event.inputs.action }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Target:** ${{ github.event.inputs.target }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Docker Hub Repository:** https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "mobile" ]]; then
            echo "* **Mobile App Image:** ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:mobile-${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
            echo "* **Mobile App Scan Results:**" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat mobile-scan.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "monitoring" ]]; then
            echo "* **Grafana Image:** ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:grafana-${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
            echo "* **Prometheus Image:** ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}:prometheus-${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY


            echo "* **Monitoring Images Scan Results:**" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "=== Grafana Scan ===" >> $GITHUB_STEP_SUMMARY
            cat grafana-scan.txt >> $GITHUB_STEP_SUMMARY
            echo "\n=== Prometheus Scan ===" >> $GITHUB_STEP_SUMMARY
            cat prometheus-scan.txt >> $GITHUB_STEP_SUMMARY

            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

  # Job de déploiement après build (pour l'action 'both')
  deploy-after-build:
    needs: build-and-push
    if: ${{ success() && github.event.inputs.action == 'both' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.TF_EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy monitoring containers
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'monitoring' }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}
          TF_MONITORING_EC2_PUBLIC_IP: ${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}
          GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_ENDPOINT: ${{ secrets.TF_RDS_ENDPOINT }}
          TF_RDS_ENDPOINT: ${{ secrets.TF_RDS_ENDPOINT }}
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID || 'dummy-id' }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET || 'dummy-secret' }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          # Vérifier si le script docker-manager.sh existe
          if [ -f "./scripts/utils/docker-manager.sh" ]; then
            chmod +x ./scripts/utils/docker-manager.sh
            ./scripts/utils/docker-manager.sh deploy monitoring
          else
            # Télécharger le script depuis GitHub
            echo "Script docker-manager.sh non trouvé, téléchargement depuis GitHub..."
            curl -s -o ./docker-manager.sh "https://raw.githubusercontent.com/Med3Sin/Studi-YourMedia-ECF/main/scripts/utils/docker-manager.sh"
            chmod +x ./docker-manager.sh
            ./docker-manager.sh deploy monitoring
          fi

      - name: Deploy app containers
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'mobile' }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}
          TF_MONITORING_EC2_PUBLIC_IP: ${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          # Vérifier si le script docker-manager.sh existe
          if [ -f "./scripts/utils/docker-manager.sh" ]; then
            chmod +x ./scripts/utils/docker-manager.sh
            ./scripts/utils/docker-manager.sh deploy mobile
          else
            # Télécharger le script depuis GitHub
            echo "Script docker-manager.sh non trouvé, téléchargement depuis GitHub..."
            curl -s -o ./docker-manager.sh "https://raw.githubusercontent.com/Med3Sin/Studi-YourMedia-ECF/main/scripts/utils/docker-manager.sh"
            chmod +x ./docker-manager.sh
            ./docker-manager.sh deploy mobile
          fi

      - name: Summary
        run: |
          echo "## Résumé du Déploiement (après construction)" >> $GITHUB_STEP_SUMMARY
          echo "* **Action:** ${{ github.event.inputs.action }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Target:** ${{ github.event.inputs.target }}" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "monitoring" ]]; then
            echo "* **Monitoring URL:** http://${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}:3000" >> $GITHUB_STEP_SUMMARY
            echo "* **Prometheus URL:** http://${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}:9090" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "mobile" ]]; then
            echo "* **Mobile App URL:** http://${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}:8080" >> $GITHUB_STEP_SUMMARY
          fi

  # Job de déploiement uniquement (pour l'action 'deploy')
  deploy:
    if: ${{ github.event.inputs.action == 'deploy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.TF_EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy monitoring containers
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'monitoring' }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}
          TF_MONITORING_EC2_PUBLIC_IP: ${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}
          GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_ENDPOINT: ${{ secrets.TF_RDS_ENDPOINT }}
          TF_RDS_ENDPOINT: ${{ secrets.TF_RDS_ENDPOINT }}
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID || 'dummy-id' }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET || 'dummy-secret' }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          # Vérifier si le script docker-manager.sh existe
          if [ -f "./scripts/utils/docker-manager.sh" ]; then
            chmod +x ./scripts/utils/docker-manager.sh
            ./scripts/utils/docker-manager.sh deploy monitoring
          else
            # Télécharger le script depuis GitHub
            echo "Script docker-manager.sh non trouvé, téléchargement depuis GitHub..."
            curl -s -o ./docker-manager.sh "https://raw.githubusercontent.com/Med3Sin/Studi-YourMedia-ECF/main/scripts/utils/docker-manager.sh"
            chmod +x ./docker-manager.sh
            ./docker-manager.sh deploy monitoring
          fi

      - name: Deploy app containers
        if: ${{ github.event.inputs.target == 'all' || github.event.inputs.target == 'mobile' }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO || 'yourmedia-ecf' }}
          TF_MONITORING_EC2_PUBLIC_IP: ${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          # Vérifier si le script docker-manager.sh existe
          if [ -f "./scripts/utils/docker-manager.sh" ]; then
            chmod +x ./scripts/utils/docker-manager.sh
            ./scripts/utils/docker-manager.sh deploy mobile
          else
            # Télécharger le script depuis GitHub
            echo "Script docker-manager.sh non trouvé, téléchargement depuis GitHub..."
            curl -s -o ./docker-manager.sh "https://raw.githubusercontent.com/Med3Sin/Studi-YourMedia-ECF/main/scripts/utils/docker-manager.sh"
            chmod +x ./docker-manager.sh
            ./docker-manager.sh deploy mobile
          fi

      - name: Summary
        run: |
          echo "## Résumé du Déploiement (déploiement uniquement)" >> $GITHUB_STEP_SUMMARY
          echo "* **Action:** ${{ github.event.inputs.action }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Target:** ${{ github.event.inputs.target }}" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "monitoring" ]]; then
            echo "* **Monitoring URL:** http://${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}:3000" >> $GITHUB_STEP_SUMMARY
            echo "* **Prometheus URL:** http://${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}:9090" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "${{ github.event.inputs.target }}" == "all" || "${{ github.event.inputs.target }}" == "mobile" ]]; then
            echo "* **Mobile App URL:** http://${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}:8080" >> $GITHUB_STEP_SUMMARY
          fi
