name: 4 - SonarQube Analysis

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project to analyze'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - backend
          - mobile

jobs:
  analyze-backend:
    name: Analyze Backend (Java)
    if: ${{ github.event.inputs.project == 'all' || github.event.inputs.project == 'backend' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}:9000
        run: |
          cd app-java
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=yourmedia-backend \
            -Dsonar.projectName='YourMedia Backend' \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

  analyze-mobile:
    name: Analyze Mobile App
    if: ${{ github.event.inputs.project == 'all' || github.event.inputs.project == 'mobile' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: app-react/package-lock.json

      - name: Install dependencies
        run: |
          cd app-react
          npm install

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://${{ secrets.TF_MONITORING_EC2_PUBLIC_IP }}:9000
        with:
          projectBaseDir: app-react
          args: >
            -Dsonar.projectKey=yourmedia-mobile
            -Dsonar.projectName='YourMedia Mobile'
            -Dsonar.sources=src
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
