name: 6 - Retrieve Secrets from Terraform Cloud

# -----------------------------------------------------------------------
# Ce workflow permet de récupérer les secrets stockés dans Terraform Cloud.
# Il est réservé aux administrateurs du projet.
# -----------------------------------------------------------------------

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Nom du secret à récupérer'
        required: true
        type: string
      show_value:
        description: 'Afficher la valeur du secret (sensible)'
        required: true
        default: false
        type: boolean

jobs:
  retrieve-secret:
    name: 'Récupérer un secret depuis Terraform Cloud'
    runs-on: ubuntu-latest
    # Limiter l'accès à ce workflow aux administrateurs uniquement
    if: github.actor == 'Med3Sin'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        
      - name: Retrieve Secret from Terraform Cloud
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          TF_WORKSPACE_ID: ${{ secrets.TF_WORKSPACE_ID }}
          SECRET_NAME: ${{ github.event.inputs.secret_name }}
          SHOW_VALUE: ${{ github.event.inputs.show_value }}
        run: |
          chmod +x ./scripts/retrieve-terraform-secrets.sh
          ./scripts/retrieve-terraform-secrets.sh "$TF_API_TOKEN" "$TF_WORKSPACE_ID" "$SECRET_NAME" "$SHOW_VALUE"
          
      - name: Summary
        run: |
          echo "## Récupération du secret depuis Terraform Cloud" >> $GITHUB_STEP_SUMMARY
          echo "* **Secret:** ${{ github.event.inputs.secret_name }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Afficher la valeur:** ${{ github.event.inputs.show_value }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Statut:** Terminé ✅" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ github.event.inputs.show_value }}" = "true" ]; then
            echo "⚠️ **ATTENTION:** La valeur du secret a été affichée dans les logs. Assurez-vous de supprimer les logs après consultation." >> $GITHUB_STEP_SUMMARY
          fi
