name: Consulter un Secret en Toute Sécurité
on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Nom du secret à consulter (ex: AWS_ACCESS_KEY_ID)'
        required: true
        type: string
      confirmation:
        description: 'Tapez "CONFIRMER" pour confirmer que vous souhaitez consulter ce secret'
        required: true
        type: string

jobs:
  view-secret:
    # Exécuter uniquement si la confirmation est correcte
    if: ${{ github.event.inputs.confirmation == 'CONFIRMER' }}
    runs-on: ubuntu-latest
    steps:
      - name: Vérification de sécurité
        run: |
          echo "AVERTISSEMENT DE SÉCURITÉ"
          echo "=========================="
          echo "Vous êtes sur le point de consulter un secret GitHub."
          echo "Cette action est journalisée et le secret sera temporairement visible dans les logs."
          echo "Assurez-vous que vous êtes autorisé à consulter ce secret."
          echo "Supprimez ce workflow immédiatement après utilisation."
          echo ""
          echo "Secret demandé : ${{ github.event.inputs.secret_name }}"
          echo "Demandé par : ${{ github.actor }}"
          echo "Date et heure : $(date)"
          echo ""
          
          # Vérifier si le secret existe
          if [[ -z "$SECRET_VALUE" ]]; then
            echo "ERREUR : Le secret '${{ github.event.inputs.secret_name }}' n'existe pas ou est vide."
            exit 1
          fi
          
          echo "Le secret existe et sera affiché dans l'étape suivante."
        env:
          SECRET_VALUE: ${{ secrets[github.event.inputs.secret_name] }}
      
      - name: Afficher le secret de manière sécurisée
        run: |
          # Créer un fichier temporaire avec des permissions restreintes
          touch secret.txt
          chmod 600 secret.txt
          
          # Écrire le secret dans le fichier
          echo "$SECRET_VALUE" > secret.txt
          
          # Obtenir la longueur du secret
          SECRET_LENGTH=$(wc -c < secret.txt)
          
          # Afficher les premiers caractères du secret (masqués partiellement)
          if [ $SECRET_LENGTH -gt 8 ]; then
            echo "Aperçu du secret : $(head -c 4 secret.txt)****$(tail -c 4 secret.txt)"
            echo "Longueur totale : $SECRET_LENGTH caractères"
          else
            echo "Secret trop court pour un aperçu sécurisé"
          fi
          
          echo ""
          echo "ATTENTION : Le secret complet sera affiché ci-dessous."
          echo "Ces logs seront accessibles aux personnes ayant accès à ce dépôt."
          echo "Supprimez ce workflow immédiatement après utilisation."
          echo ""
          echo "Valeur complète du secret '${{ github.event.inputs.secret_name }}' :"
          echo "-----------------------------------------------------------"
          echo "$SECRET_VALUE"
          echo "-----------------------------------------------------------"
          
          # Supprimer le fichier temporaire
          rm secret.txt
        env:
          SECRET_VALUE: ${{ secrets[github.event.inputs.secret_name] }}
      
      - name: Rappel de sécurité
        run: |
          echo ""
          echo "RAPPEL DE SÉCURITÉ IMPORTANT"
          echo "==========================="
          echo "1. Le secret a été affiché dans les logs de ce workflow."
          echo "2. Supprimez ce workflow immédiatement après utilisation."
          echo "3. Envisagez de faire tourner (changer) ce secret si nécessaire."
          echo ""
          echo "Pour supprimer ce workflow :"
          echo "1. Accédez à votre dépôt GitHub"
          echo "2. Supprimez le fichier .github/workflows/view-secret-securely.yml"
          echo "3. Committez la suppression avec un message comme 'Suppression du workflow temporaire de consultation des secrets'"
